name: Docker Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Login a ACR
    - name: Login to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login acrdevopscloudlab.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

    # Build imagen Docker
    - name: Build Docker image
      run: docker build -t acrdevopscloudlab.azurecr.io/cloudlab-api:${{ github.sha }} ./src/CloudLab.Api

    # Push a ACR
    - name: Push Docker image
      run: docker push acrdevopscloudlab.azurecr.io/cloudlab-api:${{ github.sha }}

    # Login en Azure
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy en App Service
    - name: Deploy to Azure Web App
      run: |
        az webapp config container set \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group rg-devops-cloud-lab \
          --docker-custom-image-name acrdevopscloudlab.azurecr.io/cloudlab-api:${{ github.sha }} \
          --docker-registry-server-url https://acrdevopscloudlab.azurecr.io

        az webapp restart \
          --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group rg-devops-cloud-lab
